# -*- mode: ruby -*-
# vi: set ft=ruby :

#vagrant up
#vagrant reload


Vagrant.configure(2) do |config|
#https://app.vagrantup.com/jamesthinkbox/boxes/ubuntu-16.04-desktop-amd64
  #config.vm.box = "jamesthinkbox/ubuntu-16.04-desktop-amd64"
  config.vm.box = "bento/ubuntu-16.04" # 16.04 LTS
  config.vm.hostname = "sdl-core-min"

  config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', ip: "192.168.1.203"

  # Increase memory for Parallels Desktop
  config.vm.provider "parallels" do |p, o|
    p.memory = "1024"
  end

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
        vb.memory = 8024
        vb.cpus = "8"
  end

  # Increase memory for VMware
  ["vmware_fusion", "vmware_workstation"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "1024"

    end
  end
end


Vagrant.configure("2") do |config|
  # other config here

  config.vm.synced_folder "./../../", "/sdl_core", type: "rsync", rsync__exclude: ".git/"

  #config.vm.provision "shell", path: "../dependencies.sh"

  config.vm.provision "shell", path: "../dependencies.sh", run: "always"
  config.vm.provision "shell", path: "../compile.sh",     run: "always"

#https://www.vagrantup.com/docs/provisioning/basic_usage.html
  config.vm.provision "shell", path: "../startup.sh",     run: "always"

#share folders with host via a networked drive.
  config.vm.provision "shell", path: "../samba.sh",     run: "always"


end
