# -*- mode: ruby -*-
# vi: set ft=ruby :

#vagrant up
#vagrant reload


Vagrant.configure(2) do |config|
#https://app.vagrantup.com/jamesthinkbox/boxes/ubuntu-16.04-desktop-amd64
  config.vm.box = "bento/ubuntu-16.04" # 16.04 LTS

  #used as the base box for other builds?
  config.vm.hostname = "sdl-core-develop"

#directly connecting doesn't seem to be working here. using host machine's ip with port forwarding works.
  #ALLOW ALL MUST BE SET MANUALLY to allow bridged connection to work.
  config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', ip: "192.168.1.223"


# Expose the following ports
#   3001: Expose SDL Core's file system
#   12345: Expose SDL Core's primary port. Used to communicate with the SDL Core instance over TCP
#   5050: Expose video streaming port
#   5080: Expose audio streaming port
#   8090: Expose time testing port
#   8888: Expose websocket port for core log streaming
#   9000: Websocket connection to the broker
#   9898: Expose miniature policy server port

#host 192.168.1.57
  config.vm.network "forwarded_port", guest: 12345, host: 12345
  config.vm.network "forwarded_port", guest: 8087, host: 8087

  config.vm.network "forwarded_port", guest: 8888, host: 8888

#3001 -> 9012
    config.vm.network "forwarded_port", guest: 3001, host: 9012
    config.vm.network "forwarded_port", guest: 9080, host: 9080


#broker api forwarded port. obsolete.
  #config.vm.network "forwarded_port", guest: 4040, host: 4040

#microservices forwarded port. expose restart core.
    config.vm.network "forwarded_port", guest: 5050, host: 5050


  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
        vb.memory = 8024
        vb.cpus = "8"
  end

end


#https://www.vagrantup.com/docs/plugins/commands.html
Vagrant.configure("2") do |config|

#TODO pass in environmental variables on vagrant up. add custom vagrant command?
#config.vm.provision "shell", inline: <<-SHELL
#  echo "export MYVAR='my_value'" >> /etc/profile.d/myvar.sh
#SHELL

  config.vm.synced_folder "./../startup", "/startup"


  # other config here
    config.vm.synced_folder "./../startup", "/startup"


#I think this synced folder might work okay it is just that the third party libraries have to recompile each time. It is hard to get an accurate measurement.
#Should have a master branch and develop branch.
  #config.vm.synced_folder "./../../", "/sdl_core", type: "rsync", rsync__exclude: ".git/"

  #config.vm.provision "shell", path: "../dependencies.sh"

#rerun provisions.
  #vagrant reload --provision-with dependencies,compile,shell

  config.vm.provision "dependencies", type: "shell", path: "../dependencies.sh", run: "once"
  config.vm.provision "compile", type: "shell", path: "../compile.sh", run: "once"

#https://www.vagrantup.com/docs/provisioning/basic_usage.html
  config.vm.provision "shell", path: "../startup.sh",     run: "always"

#share folders with host via a networked drive.
  config.vm.provision "shell", path: "../samba.sh",     run: "always"


end
