# -*- mode: ruby -*-
# vi: set ft=ruby :

#vagrant up
#vagrant reload


Vagrant.configure(2) do |config|
#https://app.vagrantup.com/jamesthinkbox/boxes/ubuntu-16.04-desktop-amd64
  config.vm.box = "jamesthinkbox/ubuntu-16.04-desktop-amd64"
  #config.vm.box = "bento/ubuntu-16.04" # 16.04 LTS
  config.vm.hostname = "sdl-core"
  #config.vm.provision "shell", inline: $script, privileged: false



  # Expose the following ports
  #   3001: Expose SDL Core's file system
  #   12345: Expose SDL Core's primary port. Used to communicate with the SDL Core instance over TCP
  #   5050: Expose video streaming port
  #   5080: Expose audio streaming port
  #   8090: Expose time testing port
  #   8888: Expose websocket port for core log streaming
  #   9000: Websocket connection to the broker
  #   9898: Expose miniature policy server port

#https://www.hostpapa.ca/knowledgebase/add-subdomain-points-ip-address/
    #config.vm.forwarded_port 80, 8080
    #config.vm.network "hostonly", "192.168.33.10"
#    config.vm.network "bridged"


    #config.vm.network "public_network"
    #after getting the config use this
#    ==> default: Available bridged network interfaces:
#    1) en0: Wi-Fi (AirPort)
#    2) p2p0
#    3) awdl0
#    4) en1: Thunderbolt 1
#    5) en2: Thunderbolt 2
#    6) bridge0

#promiscuous mode  = Allow All
    config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', ip: "192.168.1.201"


#prod ports
  #config.vm.network "forwarded_port", guest: 3001, host: 3001, auto_correct: false
  #config.vm.network "forwarded_port", guest: 12345, host: 12345, auto_correct: false
  #config.vm.network "forwarded_port", guest: 5050, host: 5050, auto_correct: false
  #config.vm.network "forwarded_port", guest: 5080, host: 5080, auto_correct: false
  #config.vm.network "forwarded_port", guest: 8090, host: 8090, auto_correct: false

  #testing ports
  #config.vm.network "forwarded_port", guest: 8888, host: 8888, auto_correct: false
  #config.vm.network "forwarded_port", guest: 9000, host: 9000, auto_correct: false
  #config.vm.network "forwarded_port", guest: 9898, host: 9898, auto_correct: false

  # Increase memory for Parallels Desktop
  config.vm.provider "parallels" do |p, o|
    p.memory = "1024"
  end

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
        #vb.memory = "1024"
        #vb.memory = 4024
        vb.memory = 8024

  end

  # Increase memory for VMware
  ["vmware_fusion", "vmware_workstation"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "1024"
    end
  end
end


Vagrant.configure("2") do |config|
  # other config here

  config.vm.synced_folder "./../../", "/sdl_core"
  config.vm.synced_folder "./../../../sdl_hmi", "/sdl_hmi"
  #config.vm.synced_folder "./../../../sdl_core_build", "/sdl_core_build"

  #make[2]: Warning: File 'src/components/interfaces/HMI_API_schema.h' has modification time 0.26 s in the future
  #TODO maybe linking to the build isn't a good idea.
end
